name: CI Docker Scout

on:
  push:
    branches:
      - main
      - fix/attestation-docs
  pull_request:

jobs:
  scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Login a Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Instalar Docker Scout
      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      # Verificar instalación
      - name: Verify installation
        run: docker scout version

      # Ejecutar análisis
      - name: Run Docker Scout Quickview
        run: docker scout quickview alpine

      - name: Run Docker Scout CVEs
        run: docker scout cves alpine

      # =========================
      #  PRUEBAS UNITARIAS
      # =========================

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Install pytest
        run: pip3 install pytest

      - name: Run unit tests
        run: pytest
