name: octoguard-test-pin
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
  actions: read
  security-events: write
jobs:
  octoguard:
    uses: docker/octoguard/.github/workflows/octoguard.yml@zizmor-app-token-online-audits
    permissions:
      contents: read
      actions: read
      security-events: write
    secrets: inherit
